import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Outer table */}
      <table className="outer-Table" width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>
          {/* Inner Table  */}
            <table className="inner-Table" max-height="800px" width="600px" border="0" cellspacing="0" cellpadding="0">
              {/* The First Row */}
              <tr className="firstRow">
                <td>
                    <h1><a className="uber" href="#">Uber</a><a className="eats">Eats</a></h1>
                </td>
              </tr>
              {/* Second Row */}
              <tr className="secondRow">
                <td>
                  <div className="uberFood">
                      <img className="uberFood" src="https://d1ralsognjng37.cloudfront.net/168585cb-b3f4-4bb2-b4ce-b433cdc714a1.jpeg"/>
                  </div>
                </td>
              </tr>
              <tr className="thirdRow">
                <td>
                  <h1>Breakfast, lunch, or dinner? Your move.</h1>
                  <h3>Take 75% off your next 2 orders when you enter YUMMYCAN_DP9 at checkout.</h3>
                  <div className="btn-links">
                  <a className="can-btn" href="#">yummycan_dp9</a>
                  <a className="order-btn" href="#">Order now</a>
                  </div>
                </td>
              </tr>
              <tr className="fourthRow">
                <td>
                    <h1 className="makeMeal">Make a meal of it</h1>
                    <h3>From sweet treats to Friday night feats, treat yourself to something delicious.</h3>
                    <a className="order-btn" href="#">Order now </a>
                    {/* Place the img here */}
                    <div className="food-img">
                      <img className="lunch-pic" src="https://cdn.vox-cdn.com/thumbor/2OpWiO6PAqdLjJmjeYNfsigAY_I=/0x0:2904x2176/1200x900/filters:focal(1220x856:1684x1320)/cdn.vox-cdn.com/uploads/chorus_image/image/63217471/190216_JM_UBEREATS_03_FRIES_BURGER_0273_V5.0.jpg"/>
                      <img className="breakfast-pic"  src="https://d1a3f4spazzrp4.cloudfront.net/chameleon/cms/uploads/2017/2/23/1487871968-DaisyDukes_Hero_2880x2304.jpg"/>
                      <img className="dinner-pic"  src="https://d1ralsognjng37.cloudfront.net/706cc37a-3d7c-4658-a197-7656788f0cb0.jpeg"/>
                    </div>
                    <p className="offer"> Offer expires at OCt 21 2021 10:00AM. The offer is valid gor up to 75% off of 2 orders only. Offer is limited to 1 order per customer. You must recieve this email directly from Uber to be eligible Other fees may apply. Pffer is valid for maximum discount of $15.You must apply the promo code in the app before completing your order. Offer may not be combined with other offers. See the Uber eats app for details. </p>

                </td>
              </tr>
              <tr className="fifthRow">
                <td>
                  <div className="footer-links">
                    <a className="help-btn" href="#">Help Center</a>
                    <a className="sub-btn" href="#">Unsubscibe</a>
                    <a className="term-btn" href="#">Terms</a>
                    <a className="privacy-btn" href="#">Privacy</a>
                    <a className="email-btn" href="#">Email Preferences</a>
                  </div>

                  <p>This is a promotional email from Uber Portier Canada Inc.</p>
                  <div className="address">
                    121 Bloor Street East Suite #1600,<br/>
                    Toronto, ON M4W 3M5<br/>
                    Uber.com
                  </div>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </div>
  )
}
